export const GET_TOP_TRACKS_START = 'GET_TOP_TRACKS';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_FAIL = 'GET_TRACKS_FAIL';

export const GET_ARTIST_START = 'GET_ARTIST_START';
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS';
export const GET_ARTIST_FAIL = 'GET_ARTIST_FAIL';
